
FROM golang:latest as go-stage

WORKDIR /app

COPY . .

WORKDIR /app/leaderboard-service

RUN go mod download
RUN go build -o leaderboard-service -ldflags '-linkmode external -extldflags "-static"'

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates libpq
COPY --from=go-stage /app/leaderboard-service/leaderboard-service /app/leaderboard-service

CMD ["/app/leaderboard-service"]
