site_name: Cubepanion API documentation
site_url: ""

nav:
  - Home: index.md
  - API Reference:
      - Chest Service: chests.md
      - Games Service: games.md
      - Leaderboard Service: leaderboard.md
      - Maps Service: maps.md

theme: readthedocs
