/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

version = "0.2.0"


plugins {
    `java-library`
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.google.guava:guava:31.1-jre")
    implementation("org.asynchttpclient:async-http-client:3.0.0.Beta2")
    implementation("com.google.code.gson:gson:2.8.9")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
    withJavadocJar()
}

tasks.register<Javadoc>("generateJavadoc") {
    sourceSets.main.get().java.srcDirs.forEach {
        source(it)
    }
    classpath += configurations.getByName("compileClasspath")
    destinationDir = file("$buildDir/docs/javadoc")
}
