FROM cubepanion-services:base as go-stage

WORKDIR /app/maps-service

COPY maps-service /app/maps-service

RUN go build -o maps-service -ldflags '-linkmode external -extldflags "-static"'

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates libpq
COPY --from=go-stage /app/maps-service/maps-service /app/maps-service

CMD ["/app/maps-service"]
