FROM ameliaah/cubepanion-services:base as go-stage

WORKDIR /app/games-service

COPY games-service /app/games-service

RUN go build -o games-service -ldflags '-linkmode external -extldflags "-static"'

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates libpq
COPY --from=go-stage /app/games-service/games-service /app/games-service

CMD ["/app/games-service"]
