FROM ameliaah/cubepanion-services:base as go-stage

WORKDIR /app/stats-service

COPY stats-service /app/stats-service

RUN go build -o stats-service -ldflags '-linkmode external -extldflags "-static"'

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates libpq
COPY --from=go-stage /app/stats-service/stats-service /app/stats-service

CMD ["/app/stats-service"]
