FROM cubepanion-services:base as go-stage

WORKDIR /app/leaderboard-service

COPY leaderboard-service /app/leaderboard-service

RUN go build -o leaderboard-service -ldflags '-linkmode external -extldflags "-static"'

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates libpq
COPY --from=go-stage /app/leaderboard-service/leaderboard-service /app/leaderboard-service

CMD ["/app/leaderboard-service"]
