FROM cubepanion-api-base as go-stage

WORKDIR /app/cubesocket

COPY cubesocket /app/cubesocket

RUN go build -o cubesocket -ldflags '-linkmode external -extldflags "-static"'

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates libpq
COPY --from=go-stage /app/cubesocket/cubesocket /app/cubesocket

CMD ["/app/cubesocket"]
