FROM ameliaah/cubepanion-services:base as go-stage

WORKDIR /app/chests-service

COPY chests-service /app/chests-service

RUN go build -o chests-service -ldflags '-linkmode external -extldflags "-static"'

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates libpq
COPY --from=go-stage /app/chests-service/chests-service /app/chests-service

CMD ["/app/chests-service"]
