name: '[Base] Push Docker image to Docker Hub'
on:
  push:
    branches:
      - "master"
    paths:
      - "core/**"

jobs:
  tests:
    uses: './.github/workflows/chest-service-test.yml'
  push_to_registry:
    name: '[Base] Push Docker image to Docker Hub'
    needs:
      - tests
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.base
          push: true
          tags: ameliaah/cubepanion-services:base