name: Weave Java build

on:
  push:
    branches: [ "master", "main" ]
    paths: ["weave/**", ".github/workflows/**"]
  pull_request:
    branches: [ "master", "main" ]
    paths: ["weave/**", ".github/workflows/**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Run test
        run: cd weave && chmod +x ./gradlew && ./gradlew test -Dtest.prod=true

      - name: Build with Gradle
        run: cd weave && chmod +x ./gradlew && ./gradlew build -Dtest.prod=true --stacktrace

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Weave lib
          path: ./weave/lib/build/libs/lib-*.jar