name: Chest Service Tests

on:
  pull_request:
    branches:
      - "master"
    paths:
      - "chests-service/**"
      - "core/**"
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"

      - name: Run test Chest Service
        run: go test -v ./chests-service
