name: '[Leaderboard Service] Push Docker image to Docker Hub'

on:
  push:
    branches:
      - "master"
    paths:
      - "leaderboard-service/**"
      - "docker/Dockerfile.leaderboard-service"
  workflow_run:
    workflows: [ "[Base] Push Docker image to Docker Hub" ]
    types:
      - completed

jobs:
  tests:
    uses: './.github/workflows/leaderboard-service-test.yml'

  push_to_registry:
    name: '[Leaderboard Service] Push Docker image to Docker Hub'
    needs: [tests]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.leaderboard-service
          push: true
          tags: ameliaah/cubepanion-services:leaderboard
