name: Leaderboard Service Tests

on:
  pull_request:
    branches:
      - "master"
    paths:
      - "leaderboard-service/**"
      - "core/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"

      - name: Run test Leaderboard Service
        run: go test -v ./leaderboard-service
