name: Route Tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"

      - name: Run test Chest Service
        run: go test -v ./chests-service

      - name: Run test Games Service
        run: go test -v ./games-service

      - name: Run test Maps Service
        run: go test -v ./map-service
